### ISSUE TITLE
[Spike] When should links open in a new tab?

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#18]
The purpose of this issue is to gather information and discuss the question of when we would like links to open in a new tab on the shared platform and within the filing flow. 

#### [Opening a link in the current tab (default)](https://cfpb.github.io/design-system/components/links#opening-a-link-in-the-current-tab-default)

> In general, links should default to opening in the current page or browser tab. This allows the user to choose whether they want to open an additional window in order to view the content. This applies to document and external links.

#### [Opening a link in a new tab](https://cfpb.github.io/design-system/components/links#opening-a-link-in-a-new-tab)

> Links should open in a new tab in situations where users enter data or make selections that would be lost if they left the page. This includes interactive tools, search filters, and forms where the user has to enter and submit information.

### Non-cf.gov guidelines

> When the link is in the middle of a form or multi-step process, and clicking the link would cause the user to lose progress in the form or process if it opened in the same tab, then open in a separate tab.

### Questions 
- Do we see the entire filing flow as a multi-page form?
- If a user enters data in a form input on a page, then follows a link that opens in the same tab, will the data they entered (but didn't submit) still be there? No
- If a user is logged in and they follow a link that opens in the same tab, are they still logged in when they click back? 
- When a user is in the filing flow will clicking a link that opens in the same tab cause the user to lose progress in the form or process? 

### Unique aspects of our platform (when compared to standard cf.gov pages)
- User is logged in (this is true of all pages other than the unauthenticated page) 
- On many pages, a user is submitting data

Ways to frame when to open in a new tab  
- When the link is in the middle of a form or multi-step process, and clicking the link would cause the user to lose progress in the form or process if it opened in the same tab, then open in a separate tab.
- When the link will take them to pages that are meant to help with filing (like links to the regulation and the filing instructions guide) as opposed to links to secondary information that isn't necessarily needed to help them complete the task of filing

### List of platform links: 
- Final rule
  - Rules and policy final rule page for 1071 (cf.gov)
- Collection and reporting requirements
- Find answers to frequently asked questions
- 1071 regulation on iRegs (cf.gov)
  - Link to specific section of the rule
- Filing instructions guide (cf.gov)
  - Filing instructions guide
  - Read about the filing process
  - Read about data validations
  - section 4, "Data validation”
  - Links to specific validations in the filing instructions guide
- Login.gov (general and account page)
  - Login.gov (homepage)
  - Create an account with Login.gov
  - Visit your Login.gov account page
- Navigating to other pages within the platform

**Comment by dan-padgett** [comment]
> Do we see the entire filing flow as a multi-page form?
Even more than a form, the filing flow falls under the category of an interactive tool. And as a tool, we can think about link behavior in terms of whether a filer is opening the link to do something that helps with using the tool. Initially I see three use cases here:
1. The link leads to information that would be used alongside the current step to make progress. 
   - Ex: The filing instructions guide on the errors and warnings pages is something where a filer is likely to go back and forth between the filing flow and the filing instruction guide. Having this information open in a new tab makes sense because of how the page will be used: the filer will likely want to come back to the current step once they've read the relevant information.
2. The link takes them to a different part of the filing flow. 
   - Ex: The links for uploading a new file throughout the flow are for cases where the filer intends to "restart" the flow. Opening these links on the same page makes sense in this case because they want to change where they are in the filing process.
3. The link takes them to a different part of the platform (or logs them out). 
   - Ex: On sign and submit they can go to update their profile. Also the navigation links for the filer's profile and logging out. These seem like cases for staying on the same page. There are a few different reasons for clicking these but they seem to fall under buckets of either completing a step of the filing process (updating incorrect institution information) or initiating a new task (leaving the platform).

There might be other cases, or a better taxonomy, but approaching this from the perspective how a link helps a user with a task might make for a fruitful approach to answering this question.

**Comment by natalia-fitzgerald** [comment]
Before I assess this, I want to dig in to these buckets a bit more. The first two buckets seem to assume that the link lives on a _filing flow_ page. Is this interpretation accurate? The third bucket seems to assume that the filer is either on a shared platform page or a filing flow page (in other words anywhere in the platform). Is that accurate? What do we consider to be _the parts of the platform_? Filing flow and Shared platform?

**Comment by dan-padgett** [comment]
@natalia-fitzgerald I like the suggestion for making the first bucket broader.

**Comment by dan-padgett** [comment]
@natalia-fitzgerald Here's an updated take based on the above comments about how the link destination supports a user completing a task. Framed as a decision tree in this case.
```mermaid
graph TD;
    A[Is the user logged in on the **current** page?]-->|No| B(Link opens in same page);
    A-->|Yes| C(Does the **destination** page require them to be logged in?);
    C-->|No| D(Link opens in a new tab)
    C-->|Yes| E(Link opens in the same page)
```
The key assumptions here are:
- If the user is logged in to our platform and the destination page **does not** require them to be logged into our platform to view the content, then it's most likely that the destination page is providing information that is supplemental to completing a task. (The FIG is an example of this sort of destination page.)
- If the user is logged in to our platform and the destination page **does** require them to be logged into our platform to view the content, then it's most likely that they are (a) moving forward with a task in our system, (b) attempting to cease working on their current task and starting another, or (c) trying to log out. 

And the idea of having links open in the same page when they are not logged in reflects the fact that we don't really know what they are doing at that point--though should ensure that they are not getting new tabs when they are trying to log in to our platform.

This also, to me, seems to follow the general guidelines mentioned in this ticket too.

Does this make more sense than the initial buckets? Do you think it misses any clear cases?

**Comment by natalia-fitzgerald** [comment]
@dan-padgett 
Using the logic you presented I took a look at all of the links on our pages and mapped them out. I didn't find any outliers. 

### Unauthenticated landing page: 
* The user is not logged in
* None of the links on this page require the user to be logged in
* So, these links can all open in the same page

#### List of links
* Sidebar
    * Final rule 
        * Rules and policy final rule page for 1071 (cf.gov)
    * Filing instructions guide
    * Collection and reporting requirements
    * View Privacy Notice
    * View Paperwork Reduction Act statement
* Login.gov (general and account page)
    * Login.gov (homepage)
    * Create an account with Login.gov
* Get help
    * Find answers to frequently asked questions
* GLEIF

### Complete your user profile
* The user is not logged in
* None of the links on this page require the user to be logged in
* These links can all open in the same page

#### List of links
* Unauthenticated home
* GLEIF
* View Privacy Notice

### Authenticated landing page: 
* The user is logged in
* This page contains a mix of links (some require a user to be logged in and others don't)

#### List of links that would open in the same page (require the user to be logged in)
* Home
* User name
* Log out
* View your financial institution profile
 
#### List of links that would open in a new tab (do not require a user to be logged in)
* Final rule
* Filing instructions guide
* Collection and reporting requirements

### View your user profile
* The user is logged in
* All of the links on this page require the user to be logged in
* So, these links should open in the same page
 
#### List of links that would open in the same page: 
* View your financial institution profile
* Visit your Login.gov account page
* Home
* User profile
* Log out

### View your financial institution profile
* The user is logged in
* This page contains a mix of links (some require a user to be logged in and others don't)

#### List of links that would open in the same page: 
* View your financial institution profile
* Home
* User profile
* Log out
 
#### List of links that would open in a new tab
* GLEIF
* Federal Reserve Board

### Update your financial institution profile
* The user is logged in
* This page contains a mix of links (some require a user to be logged in and others don't)
 
#### List of links that would open in the same page: 
* View your financial institution profile
* Home
* User name
* Log out

#### List of links that would open in a new tab
* GLEIF
* Federal Reserve Board

### Filing home
* The user is logged in
* This page contains a mix of links (some require a user to be logged in and others don't)

#### List of _links_ that would open in the same page: 
* Start filing, Continue filing, and other button text

#### List of links that would open in a new tab
* Filing instructions guide
* Read about the filing process
* Read about data validations

### Provide type of financial institution
* The user is logged in
* This page contains a mix of links (some require a user to be logged in and others don't)

#### List of links that would open in the same page: 
* Home
* Filing
* User profile
* Log out
* Update your financial institution profile
 
#### List of links that would open in a new tab
* Link to iRegs 

### Upload file
* The user is logged in
* This page contains a mix of links (some require a user to be logged in and others don't)

#### List of links that would open in the same page: 
* Home
* Filing
* User profile
* Log out

#### List of links that would open in a new tab
* Filing instructions guide

Resolve errors and Review warnings
* The user is logged in
* These pages contain a mix of links (some require a user to be logged in and others don't)

 ### List of links that would open in the same page: 
* Home
* Filing
* User profile
* Log out

### List of links that would open in a new tab
* Links to parts of filing instructions guide  

### Provide filing details
* The user is logged in
* These pages contain a mix of links (some require a user to be logged in and others don't)
 
#### List of links that would open in the same page: 
* Home
* Filing
* User profile
* Log out

#### List of links that would open in a new tab
* Links to iRegs
* Link to Privacy Notice


### Sign and submit
* The user is logged in
* These pages contain a mix of links (some require a user to be logged in and others don't)
 
#### List of links that would open in the same page: 
* Home
* Filing
* User profile
* Log out
* Update your financial institution profile
* Update your filing details
* Upload a new file

#### List of links that would open in a new tab
* Links to iRegs

**Comment by dan-padgett** [comment]
This is great @natalia-fitzgerald. I think that all looks good with one consideration for "Complete your user profile". We might want to treat this as a special case since a user would lose any data entered into the fields if they clicked a link. For that reason, the Privacy Notice seems like it should open in a new tab. Since all of the other links are outside of the form fields, it's probably safe to say that they intend to navigate away from the page if they click on them.

**Comment by natalia-fitzgerald** [comment]
@dan-padgett 
As we discussed in chat, the ideal time for a user to visit the "View Privacy Notice" would be _before_ they enter any personal information. 

A few weeks ago we proposed an approach where the "View Privacy Notice" would be positioned outside of the form well and in the intro text for the section. This positioning would further emphasize that the user should read the content on the Privacy Notice page _before_ entering and submitting their information.

If this is the only exception to our logic to me it shows more that the positioning of this link is faulty instead of the logic needing an exception. If we move the "View Privacy Notice" link out of the form well and into the intro text I would expect it to open in the same tab and for any data entered below to not be preserved. 

### Privacy Notice positioning
| Current positioning | UX recommendation|  
|------------| ------------|
|<img width="504" alt="Screenshot 2024-11-12 at 4 32 23 PM" src="https://github.com/user-attachments/assets/722f4756-4837-42c8-9401-c3b3cde576b7">|<img width="459" alt="Screenshot 2024-11-12 at 4 29 48 PM" src="https://github.com/user-attachments/assets/ad60fa24-489f-45d8-b571-a6e495cea2f0">|

**Comment by dan-padgett** [comment]
Concur on having another reason to move the Privacy Notice link outside of the well. I'm also on board with the reasoning you suggested in chat for having this link open in the same page: that even though it's in the well, it is still before the form fields so we're encouraging users to click on it before entering any data. So the mapping you wrote above can be our recommendation for how to handle links.

**Comment by natalia-fitzgerald** [comment]
This will also be documented in the story issue. 

### Acceptance criteria
- Given that a user *is* logged in to our platform and the destination page *does not* require them to be logged in to our platform to view the content, then the link should open in a separate tab. 
- Given that a user *is* logged in to our platform and the destination page *does* require them to be logged in to our platform to view the content, then the link should open in the same tab. 
- Given that a user *is not* logged in to our platform, then the link should open in the same tab.

In this criteria "logged in to our platform" means that they are logged in to Keycloak, Login.gov, and they have been authenticated. Complete your user profile and the complete your user profile confirmation pages do not meet this criteria since the user has not been authenticated.
