### ISSUE TITLE
[Spike] Determine which fields are required to enable submission

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#2]
## Task 
Determine which fields are **required** to be populated with either a value or "not applicable" in order to enable the submission of a filing.  

## Primary question
- Which information is **required** in order to enable the submission of a filing. 

The platform already blocks filers from advancing to sign and submit without having the following information populated in the system: 
   
### Required to register 
- LEI
  - Name
  - Headquarter's address
        
### Required to reach upload file step
- Type of financial institution
    
### Required to reach sign and submit step
- Name and business contact information
- Voluntary reporter status

#### Federal prudential regulator?
  - This field will always show the Federal prudential regulator (pulled from NIC) or "Not applicable" (not present in NIC). **Our system will not prevent a filer from submitting due to incomplete or inaccurate Federal prudential regulator information.** 
#### TIN?
  - This field will always show the TIN or will be blank. Could be blank if financial institution is not in NIC and filer did not provide TIN on the update your financial institution profile page before navigating the filing steps. If we decide to block this user from submitting, we should consider flagging this with a warning alert on the View financial institution profile page (non blocking) and then with an error alert at sign and submit (blocking). **Our system can block a user with a blank TIN from submitting a filing.** 
#### RSSD ID?
  - This field will always show the RSSD ID number or "Not applicable." A filer is responsible for providing their RSSD ID if they have one, when our system is showing "Not applicable." **Our system will not prevent a filer from submitting due to incomplete or inaccurate RSSD ID information.** 
#### Parent entity information?
  - This field will always show the specific parent entity information or "Not applicable." A filer is responsible for providing this information if applicable. But our system has no way of preventing a user from submitting their filing with incomplete or inaccurate parent entity information. **Our system will not prevent a filer from submitting due to incomplete or inaccurate immediate or top-holding parent entity information.**
  
### So, the only field that will be need to block a user from filing at sign and submit is TIN. All other fields are already required prior to sign and submit OR always show either a value or "Not applicable". 
Should users that can provide their TIN in our system (those without RSSD IDs) still have access to the pressure valve at sign and submit or should they make the update at the Update your financial institution profile page? How do we differentiate (to a user) a pressure valve versus a standard user supplied update?

## Secondary questions 
- Which data can a user edit/provide within the platform? 
  - TIN (some filers)
  - Type of financial institution (all filers)
  - Voluntary reporter status (all filers)
  - Point of contact information (all filers)
  - Parent entity information (some filers)
- Activity period information that a user can not flag or correct  (via the "pressure valve")?
  - LEI (still need to confirm activity period LEI or current LEI)
  - Type of financial institution
  - Point of contact information
  - Voluntary reporter status
  - How about those that directly provide their TIN because they have no RSSD ID?
  - How about those that directly provide parent entity information?  
- Can we use "Not applicable" for missing information in any of the parent entity and top holder parent entity fields? 

## What the rule says
The regulation requires filers to provide certain identifying information with their submission. 
> #### Financial institution identifying information.
> A financial institution shall provide each of the following with its submission.
> 
> (1) Its name.
> (2) Its headquarters address.
> (3) The name and business contact information of a person that the Bureau or other regulators may contact about the financial institution's submission.
> (4) Its Federal prudential regulator, if applicable.
> (5) Its Federal Taxpayer Identification Number (TIN).
> (6) Its Legal Entity Identifier (LEI).
> (7) Its Research, Statistics, Supervision, and Discount identification (RSSD ID) number, if applicable.
> (8) Parent entity information, if applicable, including:
>   (i) The name of the immediate parent entity;
>   (ii) The LEI of the immediate parent entity, if available;
>   (iii) The RSSD ID number of the immediate parent entity, if available;
>   (iv) The name of the top-holding parent entity;
>   (v) The LEI of the top-holding parent entity, if available; and
>   (vi) The RSSD ID number of the top-holding parent entity, if available.
> (9) The type of financial institution that it is, indicated by selecting the appropriate type or types of institution from the list provided.
> (10) Whether the financial institution is voluntarily reporting covered applications from small businesses.
> 

### Financial institution data points

Field name | User can edit in platform | User can note/flag changes to historical data (pressure valve) | Field contents | Data source | Notes | Field must contain value in order to file
-- | -- | -- | -- | -- | -- | -- 
Financial institution name | No  | Yes  | Populated  | Always pulled from GLEIF |   | Yes
Headquarters address | No | Yes  | Populated | Always pulled from GLEIF |   | Yes
Legal Entity Identifier (LEI) | No |  No | Populated | Always pulled from GLEIF |   | Yes
Legal Entity Identifier Status | No |  No | Issued or Lapsed | Always pulled from GLEIF |  | N/A
Research, Statistics, Supervision, Discount Identification (RSSD ID) number | Yes (conditional) | Yes | Populated or "Not applicable" | NIC or filer supplied (conditional) | | No (can show "Not applicable")
Federal Taxpayer Identification Number (TIN) | Yes (conditional) | Yes | Populated or Blank | NIC or filer supplied (mainly non-depositories) | Supplied by filer if absent from NIC. Not all institutions are listed in NIC, so many (non-depositories) will need to provide. | Yes (cannot file if blank)
Federal prudential regulator | No | Yes | Populated or "Not applicable" | Always pulled from NIC | | No (can show "Not applicable")
Type of Financial Institution | Yes (all filers) | No, because it can be directly edited in the platform  | Populated or Blank | Filer |   | Yes (cannot file if blank)
Immediate Parent Entity Name | Yes (conditional) | Yes | Name or "Not applicable" | GLEIF, NIC, or filer supplied (conditional) | Supplied by filer if absent from NIC/GLEIF | No (can show "Not applicable")
Immediate Parent Entity LEI | Yes (conditional) | Yes | Populated or "Not applicable"  | GLEIF or filer supplied (conditional) | Supplied by filer if FI has a reporting exception in GLEIF that prevents the top holder from being linked but does in fact have a top holder with an LEI. | No (can show "Not applicable")
Immediate Parent Entity RSSD ID | Yes (conditional) |  Yes | Populated or "Not applicable"  | NIC or filer supplied (conditional) | Supplied by filer if FI is absent from NIC but FI's parent is in NIC | No (can show "Not applicable")
Top-holding Parent Entity Name | Yes (conditional) | Yes | Populated or "Not applicable" | GLEIF or filer supplied (conditional) | Some institutions will have top holders that are not listed in either NIC or GLEIF. Supplied by filer if absent from NIC/GLEIF. | No (can show "Not applicable")
Top-holding Parent Entity LEI |  Yes (conditional) | Yes | Populated or "Not applicable"  | GLEIF or filer supplied (conditional) |  Supplied by filer if FI has a reporting exception in GLEIF that prevents the top holder from being linked but does in fact have a top holder with an LEI | No (can show "Not applicable")
Top-holding Parent Entity RSSD ID | Yes (conditional) | Yes | Populated or "Not applicable" | NIC or filer supplied (conditional) | Supplied by filer if FI is absent from NIC but FI's top holder is in NIC | No (can show "Not applicable") 

### Filing specific data points
Field name | User can edit in platform | User can note/flag changes to historical data (pressure valve) | Field contents | Data source | Notes | Field must contain value in order to file 
-- | -- | -- | -- | -- | -- | -- 
Voluntary reporter status | Yes (all filers) | No, because it can be directly edited in the platform | Voluntary reporter or Not a voluntary reporter | Filer |   | Yes
Point of contact | Yes (all filers) | No, because it can be directly edited in the filing flow | All required content is populated | Filer |   | Yes

**Comment by natalia-fitzgerald** [comment]
@nongarak 
I can close this out with a confirmation that TIN is a required field (must be populated) at the Sign and submit step.

**Comment by nongarak** [comment]
Per our conversation today, TIN is a required field (must be populated) at the sign and submit step.

**Comment by natalia-fitzgerald** [comment]
I have updated this table to reflect RSSD ID remaining as conditionally editable. 
https://github.com/cfpb/sbl-ux/issues/2#issue-2573954515

I think we have answered the questions we wanted to answer as a part of this ticket so I will close.
