### ISSUE TITLE
Review design implementation of sign and submit

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#21]
Review design implementation of new features on sign and submit: 
- Success alert at the top and the bottom of the page
- Enabled checkboxes
- Enabled "Submit filing" button
- Warning alert for beta filers assuring them that they can click the "Submit filing" button and continue to test the beta platform

![screencapture-sbl-frontend-eks-dev-public-aws-cfpb-gov-filing-2024-1234FRONNATALIATST02-submit-2024-10-30-15_08_58](https://github.com/user-attachments/assets/3e0b3c22-a129-477a-b083-573789ab942d)

**Comment by natalia-fitzgerald** [comment]
## Here's a running list for my design review of the new sign and submit features
* Spacing issue on success alert
    * The alert component doesn’t account for instances where the alert includes 2 paragraphs. So the spacing between the heading and the first paragraph is 5px and the space between the two paragraphs is 15px. This doesn’t work. 
    * In Figma, I have it set to 10px and 10px. We could try 5px, 5px as a first step but I suspect this will be too tight. 
    
#### Success alert
| Dev pub | Figma |  
|------------| ------------|
|<img width="801" alt="Screenshot 2024-10-30 at 11 54 38 AM" src="https://github.com/user-attachments/assets/339236fb-1b43-471a-857d-aba5c46ac564">|<img width="755" alt="Screenshot 2024-10-30 at 2 59 58 PM" src="https://github.com/user-attachments/assets/9d095435-b440-4a8d-a3f5-559be1e6cb1e">|

* Icon issue on warning alert without heading
#### Success alert
| Dev pub | Figma |  
|------------| ------------|
|<img width="642" alt="Screenshot 2024-10-30 at 11 54 04 AM" src="https://github.com/user-attachments/assets/7fc5da05-9694-437d-bf55-d7344514990f">|<img width="642" alt="Screenshot 2024-10-30 at 12 33 41 PM" src="https://github.com/user-attachments/assets/98ef4d78-2b5f-4a4c-a18a-ef941e9095f2">|

* Change text: _The point of contact information for my filing is accurate and complete._
| Dev pub | Figma |  
|------------| ------------|
|<img width="959" alt="Screenshot 2024-10-30 at 3 06 43 PM" src="https://github.com/user-attachments/assets/56e1be2c-d112-425f-9c4a-2a2af2379a1c">|<img width="779" alt="Screenshot 2024-10-30 at 3 06 19 PM" src="https://github.com/user-attachments/assets/417c342a-a1a1-440d-8ca7-61cfc620c8d8">|

* Alert behavior if a user uploads a new file during beta 
    * Just adding this as a note here but it doesn’t block the design review

**Comment by natalia-fitzgerald** [comment]
### After yesterday's Desv/Design Sync we have the following next steps: 
- Include LOU language into the sign and submit language around lapsed LEIs
- The backend will be set up to accept all registration statuses (for example, issued, lapsed, retired, merged, etc.)
- Rework content for the error alert to specify that LEI registration status must be issued in order to file…and make the action step more general --- contact LOU, go to GLEIF to figure out your LOU OR email our support staff

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
As a review the sign and submit changes on DevPub, I'll add any remaining items here. 

- [ ] Remove the year from the end of the success alert heading


Things to think about: 
- What is the alert behavior if a user uploads a new file during beta period? My assumption is that when a user uploads a new file the previous successful submission is wiped.

**Comment by dan-padgett** [comment]
Related to @natalia-fitzgerald's question: After I successfully submit my filing, if I go back to sign and submit, shouldn't the checkboxes remain checked if nothing has changed? (Currently, if I submit, then go to filing home > File your data > Continue filing, when I'm back on sign and submit I see the success message but the checkboxes are unchecked.

**Comment by billhimmelsbach** [comment]
> * What is the alert behavior if a user uploads a new file during beta period? My assumption is that when a user uploads a new file the previous successful submission is wiped.

When you say "submission" you mean "filing" right? Right now, their previous filing isn't wiped: we discussed handling review and reopening filings next quarter. Are we going to follow the HMDA model where re-uploading = reopening a filing?

**Comment by billhimmelsbach** [comment]
> When you say "submission" you mean "filing" right? Right now, their previous filing isn't wiped: we discussed handling review and reopening filings next quarter. Are we going to follow the HMDA model where re-uploading = reopening a filing?

The idea that reuploading a register files overwrites an existing filing is what HMDA does, but we're not restricted to that at all.

**Comment by billhimmelsbach** [comment]
Also just as an option, if you'd rather not have any sign and submit behavior yet without reopening / reviewing a filing being designed / implemented, I can put this work behind a flag so that the behavior at least won't be visible to users on the beta site.

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach @dan-padgett 

**In advance of working on reopen or review a filing in Q1** it would make sense that uploading a new register file (on the Upload file step) would clear the submission of the filing ("Submit filing" action). So I would expect that page to be cleared to the default state (no checkmarks, no success alert, etc.). If we want to leave the "Provide filing details" information" populated I would be ok with that since that is something that is saved. Let's add a sentence to the success alert to prepare a user for what will happen if they upload a new file after completing the filing process. 

<img width="665" alt="Screenshot 2024-11-22 at 11 58 05 AM" src="https://github.com/user-attachments/assets/6cebac34-14d9-4cd5-b6f0-f114bc6ed46a">

**Comment by natalia-fitzgerald** [comment]
> > @billhimmelsbach @dan-padgett
> > **In advance of working on reopen or review a filing in Q1** it would make sense that uploading a new register file (on the Upload file step) would clear the submission of the filing ("Submit filing" action). So I would expect that page to be cleared to the default state (no checkmarks, no success alert, etc.). If we want to leave the "Provide filing details" information" populated I would be ok with that since that is something that is saved. Let's add a sentence to the success alert to prepare a user for what will happen if they upload a new file after completing the filing process.
> > <img alt="Screenshot 2024-11-22 at 11 58 05 AM" width="665" src="https://private-user-images.githubusercontent.com/77348967/389024893-6cebac34-14d9-4cd5-b6f0-f114bc6ed46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTUwOTYsIm5iZiI6MTczMjI5NDc5NiwicGF0aCI6Ii83NzM0ODk2Ny8zODkwMjQ4OTMtNmNlYmFjMzQtMTRkOS00Y2Q1LWI2ZjAtZjExNGJjNmVkNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE2NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzAyMTk5OTRkMGQ5NjcyNWQxOTk4Y2NkY2IwMDE1ZTI2OTE3MTQwMTYwMzk3YWQwZTBiMWJiOWIyYWRjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CUjCjQXy-CAqb_uUjO_i0Zaylch3VOyay5lQN6MfKkw">
> 
> Sounds good to me, are you suggesting adding this functionality now before deployment?

@billhimmelsbach 
Here's the text: 
Uploading a new file will also remove this filing.

**Comment by billhimmelsbach** [comment]
> > > @billhimmelsbach @dan-padgett
> > > **In advance of working on reopen or review a filing in Q1** it would make sense that uploading a new register file (on the Upload file step) would clear the submission of the filing ("Submit filing" action). So I would expect that page to be cleared to the default state (no checkmarks, no success alert, etc.). If we want to leave the "Provide filing details" information" populated I would be ok with that since that is something that is saved. Let's add a sentence to the success alert to prepare a user for what will happen if they upload a new file after completing the filing process.
> > > <img alt="Screenshot 2024-11-22 at 11 58 05 AM" width="665" src="https://private-user-images.githubusercontent.com/77348967/389024893-6cebac34-14d9-4cd5-b6f0-f114bc6ed46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTUwOTYsIm5iZiI6MTczMjI5NDc5NiwicGF0aCI6Ii83NzM0ODk2Ny8zODkwMjQ4OTMtNmNlYmFjMzQtMTRkOS00Y2Q1LWI2ZjAtZjExNGJjNmVkNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE2NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzAyMTk5OTRkMGQ5NjcyNWQxOTk4Y2NkY2IwMDE1ZTI2OTE3MTQwMTYwMzk3YWQwZTBiMWJiOWIyYWRjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CUjCjQXy-CAqb_uUjO_i0Zaylch3VOyay5lQN6MfKkw">
> > 
> > 
> > Sounds good to me, are you suggesting adding this functionality now before deployment?
> 
> @billhimmelsbach Here's the text: Uploading a new file will also remove this filing.

Is this something you want added before the end of this quarter? It would be a backend ask as well.

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach @jcadam14 
I imagine the next step is to estimate the level of effort for front and backend and then Angel can decide on the timing based on anything else that would be affected. 

+ @angelcardoz

**Comment by jcadam14** [comment]
> > > > @billhimmelsbach @dan-padgett
> > > > **In advance of working on reopen or review a filing in Q1** it would make sense that uploading a new register file (on the Upload file step) would clear the submission of the filing ("Submit filing" action). So I would expect that page to be cleared to the default state (no checkmarks, no success alert, etc.). If we want to leave the "Provide filing details" information" populated I would be ok with that since that is something that is saved. Let's add a sentence to the success alert to prepare a user for what will happen if they upload a new file after completing the filing process.
> > > > <img alt="Screenshot 2024-11-22 at 11 58 05 AM" width="665" src="https://private-user-images.githubusercontent.com/77348967/389024893-6cebac34-14d9-4cd5-b6f0-f114bc6ed46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTUwOTYsIm5iZiI6MTczMjI5NDc5NiwicGF0aCI6Ii83NzM0ODk2Ny8zODkwMjQ4OTMtNmNlYmFjMzQtMTRkOS00Y2Q1LWI2ZjAtZjExNGJjNmVkNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE2NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzAyMTk5OTRkMGQ5NjcyNWQxOTk4Y2NkY2IwMDE1ZTI2OTE3MTQwMTYwMzk3YWQwZTBiMWJiOWIyYWRjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CUjCjQXy-CAqb_uUjO_i0Zaylch3VOyay5lQN6MfKkw">
> > > 
> > > 
> > > Sounds good to me, are you suggesting adding this functionality now before deployment?
> > 
> > 
> > @billhimmelsbach Here's the text: Uploading a new file will also remove this filing.
> 
> Is this something you want added before the end of this quarter? It would be a backend ask as well.

Depends on the implementation.  Right now the filing object holds a list of "signature" user actions, and a confirmation id.  If the frontend is using that confirmation id to determine what to display on the final page, then yeah the backend could just wipe it out, if it exists, on each new submission (do we want to maintain old confirmation ids?).  Or if the frontend is just using the existence of signatures, it could look at time of the latest submission compared to the latest signature (they're in time order, descending), then just a frontend task.  Whatever makes it easiest on frontend to lose that state, we should be able to swing on our side.

**Comment by billhimmelsbach** [comment]
> Depends on the implementation. Right now the filing object holds a list of "signature" user actions, and a confirmation id. If the frontend is using that confirmation id to determine what to display on the final page, then yeah the backend could just wipe it out, if it exists, on each new submission (do we want to maintain old confirmation ids?). Or if the frontend is just using the existence of signatures, it could look at time of the latest submission compared to the latest signature (they're in time order, descending), then just a frontend task. Whatever makes it easiest on frontend to lose that state, we should be able to swing on our side.

Yeah, there's implementation details on review/reopen to talk out here that I'd like to save for next quarter if we can, since it's not planned to be tackled yet. Plenty of things to do before the first week in January already.

**Comment by natalia-fitzgerald** [comment]
This has been pushed live to beta and I have reviewed. So, closing this ticket.
