### ISSUE TITLE
Review design implementation of making most data fields default to "not applicable"

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#22]
Review design implementation of "not applicable"-- https://github.com/cfpb/sbl-frontend/issues/1013
- Updated the fallback values for most fields to "Not applicable"
- Ensured Type of Financial Institution, Federal Taxpayer Identification Number (TIN) show as blank values when missing
- Updated language for Legal Entity Identifier Status from "Active/Inactive" to "Issued/Lapsed"
- Refer to https://github.com/cfpb/sbl-ux/issues/2 for which unpopulated fields should be shown as blank

**Comment by natalia-fitzgerald** [comment]
@dan-padgett 
After reviewing @meissadia's implementation, I am considering whether we may want to show some something for the two fields that are currently defaulting to blank when the user has not provided the information. This includes TIN and Type of financial institution. 

What would you think of showing "Not provided" for fields where the user has not yet provided the required information. 

#### Not provided
| Before we incorporate warning alerts | With warning alerts |  
|------------| ------------|
|<img width="487" alt="Screenshot 2024-10-30 at 5 23 28 PM" src="https://github.com/user-attachments/assets/93e44683-4f2b-40f8-aa94-b29e439e824c">|<img width="587" alt="Screenshot 2024-10-30 at 2 05 24 PM" src="https://github.com/user-attachments/assets/1e058e5c-45a3-4259-9223-6d96b81ab0b7">|

**Comment by dan-padgett** [comment]
@natalia-fitzgerald I think we want the warning if we go this route. Otherwise there's a chance that "Not provided" is seen as an acceptable state. And given that, I wonder whether just having the alert would be better--maybe even going the route of a blank value with the warning below it. What do you think about those two options?

**Comment by natalia-fitzgerald** [comment]
Yeah, I actually considered that too but that also seemed to lack context. 
<img width="512" alt="Screenshot 2024-10-31 at 11 45 21 AM" src="https://github.com/user-attachments/assets/d69d29ed-5b92-4e06-9420-e60466dd18d6">

**Comment by natalia-fitzgerald** [comment]
@meissadia @billhimmelsbach 
We would like to implement this with "Not provided" instead of blank and the inline warning alert. The alert text is placeholder at this point but I will review with UX today. 

<img width="638" alt="Screenshot 2024-10-30 at 1 48 06 PM" src="https://github.com/user-attachments/assets/1c512da7-88a4-41ed-97cd-d5bdf10e1e96">

+ @dan-padgett @angelcardoz

**Comment by natalia-fitzgerald** [comment]
@dan-padgett @angelcardoz 

Warning alert content for review: 

**LEI** 
- Lapsed
- Your financial institution must have an active LEI to file. Visit GLEIF for details on how to reactivate your LEI or email our support staff for assistance.
 
**TIN** 
- Not provided
- You must provide a TIN for your financial institution to file. For instructions on how to provide this information visit update your financial institution profile.
 
**Type of financial institution** 
- Not provided
- You must provide your type of financial institution to file. To provide this information visit update your financial institution profile.

**Comment by natalia-fitzgerald** [comment]
@dan-padgett @angelcardoz 
Here's an updated mock-up based on our changes: 
[![Image](https://github.com/user-attachments/assets/4f8952e3-6cc5-4cd1-a245-38f2f44774e4)
](url)

**Comment by dan-padgett** [comment]
Capturing some information relevant to the LEI alert:
- "Active" is a term to describe an entity's status: the entity is active, the LEI is not
- For the purposes of filing, it's the LEI registration status that matters, and the registration status must be "Issued"
   - The LEI registration status could be several different values, but the ones that we are concerned with are "Lapsed" and "Issued"
- For design, there is a question about whether users only need to see that they need to renew their LEI registration to know what to do, or whether they also need to see the specific registration status so they also know what our system requires.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
Updated based on where we landed on sign and submit. 

![Image](https://github.com/user-attachments/assets/7f5cce71-db6b-4a6a-bc34-8f3192435a38)

**Comment by natalia-fitzgerald** [comment]
Update: 
- Reviewed screenshots here: https://github.com/cfpb/sbl-frontend/pull/1052
- Next step will be to review on DevPub when this is pushed there.

**Comment by natalia-fitzgerald** [comment]
Reviewed DevPub implementation here: 
- https://github.com/cfpb/sbl-frontend/pull/1052#issuecomment-2484213497
- https://github.com/cfpb/sbl-frontend/pull/1056#issuecomment-2477645085

Screenshots of what's on DevPub
![Image](https://github.com/user-attachments/assets/bd05e81c-c0e2-4a56-b4b2-17a7be2ee9d5)
![Image](https://github.com/user-attachments/assets/38aca821-d607-49ce-be71-84630268501b)
