### ISSUE TITLE
Write content for email confirmation of successful submission

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#23]
## Task 
Write content for email confirmation of submitted filing

#### Parent story (for reference)
> As a filer, I want to receive email confirmation that my submission was successful, so that I know the filing process is complete.

### Acceptance criteria

- Receive an email with confirmation ID and platform specific language ( submit ID, timestamp, beta language)
- Update UX Research doc with question about who to send the confirmation email to.

### Identify details of alert message: 
- Who sends: noreply@cfpb
- Subject: {BETA}......  
- Who receives the alert? Which contacts are main line vs. CC. The main submitter, associated accounts, primary contact
- Primarily select initial submitter and then request who else received the alert via forwarding
- Body: Basic email text

**Comment by natalia-fitzgerald** [comment]
Here's the latest language that @angelcardoz crafted with feedback from me and @dan-padgett 

From: noreply@cfpb.gov
To: Person who submitted the file
Subject: {BETA} Small Business Lending Data Filing Confirmation

Congratulations! This email confirms that the filing submitted by John Smith on June 26, 2026 at 4:36 PM EST was successful. The confirmation number is 123456789TESTBANK123-2024-134-1715013943.765721.
 
The beta platform is for testing purposes only and user-supplied data may be removed at any time. Take a moment to email our support staff at sblhelp@cfpb.gov with your feedback or upload a new file to continue testing.

**Comment by natalia-fitzgerald** [comment]
Here's the latest language that @angelcardoz crafted. @dan-padgett and I are currently reviewing. 

### Email confirmation (production platform) 
From: noreply@cfpb.gov
To: Person who submitted the file, Point of Contact
Subject: [BETA] Small Business Lending Data Filing Confirmation
 
Congratulations! This email confirms that the filing submitted by John Smith on June 26, 2026 at 4:36 PM EST was successful. The confirmation number is 123456789TESTBANK123-2024-134-1715013943.

To make any changes to the filing, please return to the Small Business Lending Data Filing Platform and follow the provided instructions. If you have any questions or need additional support, email our support staff at sblhelp@cfpb.gov.

**Comment by natalia-fitzgerald** [comment]
@hkeeler @jcadam14 
We have now written the email language for beta and production. Can you review when you have a moment?

**Comment by jcadam14** [comment]
Looks good to me, nothing in there we can't do on the backend

**Comment by hkeeler** [comment]
Agreed. Looks good.

**Comment by jcadam14** [comment]
This is being implemented as part of https://github.com/cfpb/regtech-mail-api/issues/45, PR is https://github.com/cfpb/regtech-mail-api/pull/49

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
The production implementation of the email confirmation has been implemented on dev. I tested it out and this is the email that I received. Since this is for production shouldn't we remove [DEV] from the subject line?

<img width="767" alt="Screenshot 2024-12-03 at 4 01 56 PM" src="https://github.com/user-attachments/assets/666c09c2-052c-44f2-92b0-ecbed628ba78">

**Comment by dan-padgett** [comment]
Is "[DEV]" there just as a way to know which environment it was sent from?

**Comment by natalia-fitzgerald** [comment]
Yes, I confirmed with @jcadam14 that in production "[DEV]" will not show up in the subject line.

**Comment by angelcardoz** [comment]
Looks good.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett
 
Ok, Here's the beta email confirmation with [BETA] in the subject line: 
<img width="759" alt="Screenshot 2024-12-03 at 5 12 08 PM" src="https://github.com/user-attachments/assets/42f35604-05fc-49e1-8889-fa3011d9b7c8">

And here's the production email confirmation with just the subject line:
<img width="760" alt="Screenshot 2024-12-03 at 5 14 17 PM" src="https://github.com/user-attachments/assets/3334b6d4-b553-4e5b-89f4-0e3e3d94d571">

@angelcardoz @dan-padgett  
- Do you want there to be any actual links to the platform in these emails? 
- Should we spell out "the beta for the Small Business Lending Filing Platform" or just leave it as "beta platform"?
- In the production email should we say "this filing" instead of "the filing"?

If the answer is "no" to all of these questions are we good to go?

**Comment by angelcardoz** [comment]
**Do you want there to be any actual links to the platform in these emails?** Per our convo with Hans, if I remember correctly, we can't include links. It is text only. 
**Should we spell out "the beta for the Small Business Lending Filing Platform" or just leave it as "beta platform"?** I think it is fine the way it is. "Beta" might get lost with the longer name.
**In the production email should we say "this filing" instead of "the filing"? We use "this filing" in the confirmation alert on the page.** I think "the" is correct. We refer to it that way in the intro paragraph. 

For the beta confirmation email, do we want to say "...or return to the beta platform and upload a new file to continue testing?" vs "...or upload a new file to continue testing"

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
I prefer --- > "...or return to the beta platform and upload a new file to continue testing" It's more descriptive.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
I took a look at the flow from when a filer submits a filing to when they see the alert on the page and then the email confirmation. I noticed some inconsistencies between the two so I explored some updates that can bring greater consistency and clarity for our users.

### Changes to alert
- Removed the year from the heading due to ambiguity about whether this references the year the data was collected or the filing period for which the data is being submitted
- Added the filer name
- Added a sentence for additional support (matches the email)
- Added the filer email address
- Added reference to the point of contact

### Changes to email
- Updated the date and time formatting to match the CFPB editorial style/AP style and the platform
- Removed the line about making changes since we would not want to suggest that this is a primary next step for most users. 

### Current implementation: Alert and Email
| Alert | Email |  
|------------| ------------|
|![Group 1651](https://github.com/user-attachments/assets/744dc4c0-345b-49d0-938a-30ee18a0ba9c)|<img width="766" alt="Screenshot 2024-12-04 at 10 16 47 AM" src="https://github.com/user-attachments/assets/0d839bd2-3a86-4da3-ad89-92cfa61e5398">|

### Proposed update: Alert and Email
| Alert | Email |  
|------------| ------------|
|![Notification (Success)](https://github.com/user-attachments/assets/c6809779-b618-4f8b-8a18-d985de648b27)|<img width="748" alt="Screenshot 2024-12-04 at 12 29 25 PM" src="https://github.com/user-attachments/assets/82a5d1b0-401a-48b9-a363-5f7191b15896">|

+ @dan-padgett

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
Here are the same changes applied to the beta alert and email message. 

### Beta implementation: Alert and Email
| Alert | Email |  
|------------| ------------|
|![Frame 1529](https://github.com/user-attachments/assets/2b1e15e2-6b80-42bf-8ec0-d3aef38ffa53)|<img width="735" alt="Screenshot 2024-12-04 at 4 40 15 PM" src="https://github.com/user-attachments/assets/262b9c90-ea78-49f5-bf94-448910851f10">|

**Comment by natalia-fitzgerald** [comment]
@jcadam14 @billhimmelsbach 
Here's the updated text for beta and production. 

### Beta implementation: Alert and Email
| Alert | Email |  
|------------| ------------|
|![Frame 1529](https://github.com/user-attachments/assets/2b1e15e2-6b80-42bf-8ec0-d3aef38ffa53)|<img width="735" alt="Screenshot 2024-12-04 at 4 40 15 PM" src="https://github.com/user-attachments/assets/262b9c90-ea78-49f5-bf94-448910851f10">|

### Production implementation: Alert and Email
| Alert | Email |  
|------------| ------------|
|![Notification (Success)](https://github.com/user-attachments/assets/c6809779-b618-4f8b-8a18-d985de648b27)|<img width="748" alt="Screenshot 2024-12-04 at 12 29 25 PM" src="https://github.com/user-attachments/assets/82a5d1b0-401a-48b9-a363-5f7191b15896">|

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
Here's the final content we discussed for the email confirmation message. 

### Beta release:  
Subject: [BETA] Small Business Lending Data Filing Confirmation   

Congratulations! This email confirms that Test Boss submitted a filing on Dec. 11, 2024 at 3:32 p.m. EST. The confirmation number for this filing is 177300BP2N2ZZQFLQI90-2024-7-1733949170.

The beta platform is for testing purposes only and user-supplied data may be removed at any time. Email our support staff at [sblhelp@cfpb.gov](mailto:sblhelp@cfpb.gov) to share feedback or return to the platform to upload a new file and continue testing.

### Production release: 
Subject: Small Business Lending Data Filing Confirmation   

Congratulations! This email confirms that Test Boss submitted a filing on Dec. 11, 2024 at 3:32 p.m. EST. The confirmation number for this filing is 177300BP2N2ZZQFLQI90-2024-7-1733949170.

If you have any questions or need additional support, email our support staff at [sblhelp@cfpb.gov](mailto:sblhelp@cfpb.gov).
