### ISSUE TITLE
Create a design mock-up for missing required information on sign and submit

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#25]
Create a design mock-up for missing required information on sign and submit. 

Include: 
- Mock-up of view on page load
- Mock-up of view on submission

### Bucket 1: Missing information required to file (that is not required prior to this step)
- We will provide specific next steps for the user
  - Lapsed LEI
    - Visit GLEIF for instructions on how to reactivate your LEI 
    - Email our support staff
  - Missing TIN
      - Visit update your financial institution profile for instructions 
      - If your financial institution does not have an RSSD ID, provide your TIN below
  
### Bucket 2: Missing information information required to file (that is required prior to this step)
- Missing anything else that shouldn't be missing by the time the user reaches this page, for example headquarter's address, Type of financial institution, or voluntary reporter status
- We will not load incomplete data 
- We will load an error alert and a link to email our support staff

**Comment by dan-padgett** [comment]
@natalia-fitzgerald For the second bucket, "missing anything that shouldn't be missing" sounds like a catch-all that's meant to say "missing anything that isn't a part of bucket 1, and we're not sure why it's missing". Should we add type of financial institution and voluntary report to the bucket 1 list, since those are things the user could correct? I know we have logic built into the flow to makes those required, but if bucket 2 is a catch all for inexplicable missing data, we may want to scope it a bit more.

**Comment by natalia-fitzgerald** [comment]
If they reach sign and submit and they haven't provided "Type of financial institution" or "Voluntary reporter" then it's a sign that something has gone wrong with the system, because these are required before a user can reach this step. I updated [the buckets](https://github.com/cfpb/sbl-ux/issues/25#issue-2627383355) but the general idea is that for anything other than the two requirements that haven't blocked a user from progressing prior to this step, we will not show incomplete data and instead show a general error alert and a link to email our support staff. 

Here are two options. I am showing this on the View your financial institution profile page and the Sign and submit page because both instances indicate a similar issue. 

#### An unknown error occurred
| View | Sign and submit |  
|------------| ------------|
|<img width="494" alt="Screenshot 2024-11-04 at 4 57 33 PM" src="https://github.com/user-attachments/assets/fb93357b-8e4b-46a8-b30a-90a550b8d158">|<img width="495" alt="Screenshot 2024-11-04 at 4 57 42 PM" src="https://github.com/user-attachments/assets/ca96691e-3cfa-41cb-9fdb-c28b02904bac">|

#### A problem occurred when trying to load...
| View | Sign and submit |  
|------------| ------------|
|<img width="498" alt="Screenshot 2024-11-04 at 4 58 34 PM" src="https://github.com/user-attachments/assets/5bdc864e-bbb3-4039-ae9e-556ba0bb23cc">|<img width="495" alt="Screenshot 2024-11-04 at 4 58 42 PM" src="https://github.com/user-attachments/assets/ebb6f0eb-c1b5-4501-85fa-de1984a54e43">|

**Comment by natalia-fitzgerald** [comment]
### After yesterday's Desv/Design Sync we have the following next steps: 
- Include LOU language into the sign and submit language around lapsed LEIs
- The backend will be set up to accept all registration statuses (for example, issued, lapsed, retired, merged, etc.)
- Rework content for the error alert to specify that LEI registration status must be issued in order to file…and make the action step more general --- contact LOU, go to GLEIF to figure out your LOU OR email our support staff

**Comment by dan-padgett** [comment]
Capturing some information relevant to the LEI alert:
- "Active" is a term to describe an entity's status: the entity is active, the LEI is not
- For the purposes of filing, it's the LEI registration status that matters, and the registration status must be "Issued"
   - The LEI registration status could be several different values, but the ones that we are concerned with are "Lapsed" and "Issued"
- For design, there is a question about whether users only need to see that they need to renew their LEI registration to know what to do, or whether they also need to see the specific registration status so they also know what our system requires.

**Comment by natalia-fitzgerald** [comment]
We have landed on two possible approaches to the LEI alert. There is still some discussion happening about what LEI statuses our system will potentially show. 


| You must renew your LEI registration | Your LEI registration status must be "Issued" |  
|------------| ------------|
|<img width="590" alt="Screenshot 2024-11-07 at 11 44 48 AM" src="https://github.com/user-attachments/assets/efe13636-b3d6-443a-9662-6be2486c1a43">|<img width="616" alt="Screenshot 2024-11-07 at 11 36 31 AM" src="https://github.com/user-attachments/assets/d3e01d1a-7240-4b90-8f15-0ed8284f477a">|


+ @angelcardoz

**Comment by billhimmelsbach** [comment]
I think option 2 is the most accurate and flexible with potentially rare statuses. 👍

**Comment by natalia-fitzgerald** [comment]
Ok, it sounds like we are landing on Option 2, in order to maximize flexibility. @angelcardoz - Can I get your review on this and we will move forward with implementing? 

| Option 2. Your LEI registration status must be "Issued" |  
|------------| 
|<img width="616" alt="Screenshot 2024-11-07 at 11 36 31 AM" src="https://github.com/user-attachments/assets/d3e01d1a-7240-4b90-8f15-0ed8284f477a">|

**Comment by angelcardoz** [comment]
@natalia-fitzgerald, I'm good with option 2. I think the use of "status" might be confusing to some people, but we can wait to hear from users.

**Comment by natalia-fitzgerald** [comment]
| Lapsed LEI or missing TIN on page load |  Server fails on page load |  Server fails on submission |  Lapsed LEI or missing TIN on submission
|------------| ------------| ------------| ------------| 
|![Group 1648](https://github.com/user-attachments/assets/68365928-d5e3-4b0d-937f-c47b3ccc11c2)|![On page load-- Server fails](https://github.com/user-attachments/assets/a6e0ab16-eb27-4b1d-a428-26059bbc66c9)|![On submission -- Server fails](https://github.com/user-attachments/assets/7d6dfebf-456f-4ce6-808e-96fe064f184d)|![On submission -- Lapsed LEI or missing TIN](https://github.com/user-attachments/assets/4aae37c1-fcf7-4d94-b28d-d6c24ac4f30f)|

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @nongarak 
In our DSR/Frontend meeting @hkeeler mentioned that our system will only show Issued, Lapsed, and Retired. The alert messaging we have decided to implement is flexible to account for "Lapsed" and "Retired." BUT, it is not particularly helpful for those with a "Retired" status.  

**Outside of the scope of this task**, the team may want to determine what the next step would be for a user that finds themselves in a "Retired" status and whether the next step depends on whether the LEI registration is retired in the middle of a filing period, in the middle of an activity year, or in a past filing that is being reopened.

**Comment by dan-padgett** [comment]
Only comment on the latest mockups is to add a comma in the second sentence for lapsed LEI registration: "If you need to renew you LEI registration, contact ..."

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
[These mock-ups](https://github.com/cfpb/sbl-ux/issues/25#issuecomment-2462888667) are ready for development.
